# Generated by Django 4.2.6 on 2023-12-06 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='joiner',
            field=models.ManyToManyField(related_name='joiner', to=settings.AUTH_USER_MODEL),
        ),
    ]
