# Generated by Django 4.2.6 on 2023-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_tag_remove_group_group_type_group_group_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_description',
            field=models.TextField(null=True),
        ),
    ]
